#!/bin/bash
# Copyright 2016 Holger Nassenstein
# Released under the GPLv3+

# Set permissions of config file
chmod 600 /etc/7linden/apt-proxy.conf

# Create a link in /etc/network/if-up.d
ln -s /opt/7linden-apt-proxy-client/bin/apt-proxy-client /etc/network/if-up.d/

# Create a link in /opt/7linden-apt-proxy-client/bin/
if ! [ -e /opt/7linden-apt-proxy-client/bin/install_proxy-conf_script ]; then
  ln -s /opt/7linden-apt-proxy-client/bin/apt-proxy-client /opt/7linden-apt-proxy-client/bin/install_proxy-conf_script
fi

# Remove previously generated apt proxy configuration
if [ -e /etc/apt/apt.conf.d/01proxy ]; then
  rm /etc/apt/apt.conf.d/01proxy
fi

# Execute script to generate new proxy configuration
if [ $(/etc/network/if-up.d/apt-proxy-client) ]; then
  /usr/bin/apt update
fi
